package com.moviecatalogservice.protobuf.java;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingmovies.proto

public interface TopMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopMoviesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   */
  int getCount();
}
