package com.moviecatalogservice.protobuf.java;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingmovies.proto

/**
 * Protobuf type {@code TopMoviesResponse}
 */
public  final class TopMoviesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TopMoviesResponse)
        TopMoviesResponseOrBuilder {
  // Use TopMoviesResponse.newBuilder() to construct.
  private TopMoviesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopMoviesResponse() {
    movies_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TopMoviesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              movies_ = new java.util.ArrayList<Movie>();
              mutable_bitField0_ |= 0x00000001;
            }
            movies_.add(
                input.readMessage(Movie.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        movies_ = java.util.Collections.unmodifiableList(movies_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Trendingmovies.internal_static_TopMoviesResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Trendingmovies.internal_static_TopMoviesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TopMoviesResponse.class, Builder.class);
  }

  public static final int MOVIES_FIELD_NUMBER = 1;
  private java.util.List<Movie> movies_;
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  public java.util.List<Movie> getMoviesList() {
    return movies_;
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  public java.util.List<? extends MovieOrBuilder> 
      getMoviesOrBuilderList() {
    return movies_;
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  public int getMoviesCount() {
    return movies_.size();
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  public Movie getMovies(int index) {
    return movies_.get(index);
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  public MovieOrBuilder getMoviesOrBuilder(
      int index) {
    return movies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < movies_.size(); i++) {
      output.writeMessage(1, movies_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < movies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, movies_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TopMoviesResponse)) {
      return super.equals(obj);
    }
    TopMoviesResponse other = (TopMoviesResponse) obj;

    boolean result = true;
    result = result && getMoviesList()
        .equals(other.getMoviesList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMoviesCount() > 0) {
      hash = (37 * hash) + MOVIES_FIELD_NUMBER;
      hash = (53 * hash) + getMoviesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TopMoviesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopMoviesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopMoviesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopMoviesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopMoviesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TopMoviesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TopMoviesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TopMoviesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TopMoviesResponse)
          TopMoviesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trendingmovies.internal_static_TopMoviesResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trendingmovies.internal_static_TopMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopMoviesResponse.class, Builder.class);
    }

    // Construct using TopMoviesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMoviesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (moviesBuilder_ == null) {
        movies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        moviesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Trendingmovies.internal_static_TopMoviesResponse_descriptor;
    }

    public TopMoviesResponse getDefaultInstanceForType() {
      return TopMoviesResponse.getDefaultInstance();
    }

    public TopMoviesResponse build() {
      TopMoviesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public TopMoviesResponse buildPartial() {
      TopMoviesResponse result = new TopMoviesResponse(this);
      int from_bitField0_ = bitField0_;
      if (moviesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          movies_ = java.util.Collections.unmodifiableList(movies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movies_ = movies_;
      } else {
        result.movies_ = moviesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TopMoviesResponse) {
        return mergeFrom((TopMoviesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TopMoviesResponse other) {
      if (other == TopMoviesResponse.getDefaultInstance()) return this;
      if (moviesBuilder_ == null) {
        if (!other.movies_.isEmpty()) {
          if (movies_.isEmpty()) {
            movies_ = other.movies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMoviesIsMutable();
            movies_.addAll(other.movies_);
          }
          onChanged();
        }
      } else {
        if (!other.movies_.isEmpty()) {
          if (moviesBuilder_.isEmpty()) {
            moviesBuilder_.dispose();
            moviesBuilder_ = null;
            movies_ = other.movies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            moviesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMoviesFieldBuilder() : null;
          } else {
            moviesBuilder_.addAllMessages(other.movies_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TopMoviesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TopMoviesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Movie> movies_ =
      java.util.Collections.emptyList();
    private void ensureMoviesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        movies_ = new java.util.ArrayList<Movie>(movies_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Movie, Movie.Builder, MovieOrBuilder> moviesBuilder_;

    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public java.util.List<Movie> getMoviesList() {
      if (moviesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(movies_);
      } else {
        return moviesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public int getMoviesCount() {
      if (moviesBuilder_ == null) {
        return movies_.size();
      } else {
        return moviesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Movie getMovies(int index) {
      if (moviesBuilder_ == null) {
        return movies_.get(index);
      } else {
        return moviesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder setMovies(
        int index, Movie value) {
      if (moviesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoviesIsMutable();
        movies_.set(index, value);
        onChanged();
      } else {
        moviesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder setMovies(
        int index, Movie.Builder builderForValue) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.set(index, builderForValue.build());
        onChanged();
      } else {
        moviesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(Movie value) {
      if (moviesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoviesIsMutable();
        movies_.add(value);
        onChanged();
      } else {
        moviesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(
        int index, Movie value) {
      if (moviesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoviesIsMutable();
        movies_.add(index, value);
        onChanged();
      } else {
        moviesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(
        Movie.Builder builderForValue) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.add(builderForValue.build());
        onChanged();
      } else {
        moviesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(
        int index, Movie.Builder builderForValue) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.add(index, builderForValue.build());
        onChanged();
      } else {
        moviesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addAllMovies(
        Iterable<? extends Movie> values) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movies_);
        onChanged();
      } else {
        moviesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder clearMovies() {
      if (moviesBuilder_ == null) {
        movies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        moviesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder removeMovies(int index) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.remove(index);
        onChanged();
      } else {
        moviesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Movie.Builder getMoviesBuilder(
        int index) {
      return getMoviesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public MovieOrBuilder getMoviesOrBuilder(
        int index) {
      if (moviesBuilder_ == null) {
        return movies_.get(index);  } else {
        return moviesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public java.util.List<? extends MovieOrBuilder> 
         getMoviesOrBuilderList() {
      if (moviesBuilder_ != null) {
        return moviesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(movies_);
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Movie.Builder addMoviesBuilder() {
      return getMoviesFieldBuilder().addBuilder(
          Movie.getDefaultInstance());
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Movie.Builder addMoviesBuilder(
        int index) {
      return getMoviesFieldBuilder().addBuilder(
          index, Movie.getDefaultInstance());
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public java.util.List<Movie.Builder> 
         getMoviesBuilderList() {
      return getMoviesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Movie, Movie.Builder, MovieOrBuilder>
        getMoviesFieldBuilder() {
      if (moviesBuilder_ == null) {
        moviesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Movie, Movie.Builder, MovieOrBuilder>(
                movies_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        movies_ = null;
      }
      return moviesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:TopMoviesResponse)
  }

  // @@protoc_insertion_point(class_scope:TopMoviesResponse)
  private static final TopMoviesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TopMoviesResponse();
  }

  public static TopMoviesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopMoviesResponse>
      PARSER = new com.google.protobuf.AbstractParser<TopMoviesResponse>() {
    public TopMoviesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopMoviesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopMoviesResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TopMoviesResponse> getParserForType() {
    return PARSER;
  }

  public TopMoviesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

