package com.moviecatalogservice.protobuf.java;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingmovies.proto

public final class Trendingmovies {
  private Trendingmovies() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopMoviesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopMoviesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopMoviesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopMoviesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024trendingmovies.proto\"!\n\020TopMoviesReque" +
      "st\022\r\n\005count\030\001 \001(\005\":\n\005Movie\022\014\n\004name\030\001 \001(\t" +
      "\022\023\n\013description\030\002 \001(\t\022\016\n\006rating\030\003 \001(\001\"+\n" +
      "\021TopMoviesResponse\022\026\n\006movies\030\001 \003(\0132\006.Mov" +
      "ie2N\n\025TrendingMoviesService\0225\n\014GetTopMov" +
      "ies\022\021.TopMoviesRequest\032\022.TopMoviesRespon" +
      "seB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TopMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopMoviesRequest_descriptor,
        new String[] { "Count", });
    internal_static_Movie_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_descriptor,
        new String[] { "Name", "Description", "Rating", });
    internal_static_TopMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TopMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopMoviesResponse_descriptor,
        new String[] { "Movies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
