apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-deployment
  labels:
    app: movie-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog
  template:
    metadata:
      labels:
        app: movie-catalog
    spec:
      containers:
        - name: movie-catalog
          image: 838cd9550083
          ports:
            - containerPort: 9090
