package com.moviecatalogservice.protobuf.java;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingmovies.proto

public final class Trendingmovies {
  private Trendingmovies() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopMoviesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopMoviesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 count = 1;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code TopMoviesRequest}
   */
  public  static final class TopMoviesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopMoviesRequest)
      TopMoviesRequestOrBuilder {
    // Use TopMoviesRequest.newBuilder() to construct.
    private TopMoviesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopMoviesRequest() {
      count_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TopMoviesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trendingmovies.internal_static_TopMoviesRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trendingmovies.internal_static_TopMoviesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trendingmovies.TopMoviesRequest.class, Trendingmovies.TopMoviesRequest.Builder.class);
    }

    public static final int COUNT_FIELD_NUMBER = 1;
    private int count_;
    /**
     * <code>int32 count = 1;</code>
     */
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (count_ != 0) {
        output.writeInt32(1, count_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, count_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Trendingmovies.TopMoviesRequest)) {
        return super.equals(obj);
      }
      Trendingmovies.TopMoviesRequest other = (Trendingmovies.TopMoviesRequest) obj;

      boolean result = true;
      result = result && (getCount()
          == other.getCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Trendingmovies.TopMoviesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Trendingmovies.TopMoviesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trendingmovies.TopMoviesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Trendingmovies.TopMoviesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopMoviesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopMoviesRequest)
        Trendingmovies.TopMoviesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trendingmovies.internal_static_TopMoviesRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trendingmovies.internal_static_TopMoviesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Trendingmovies.TopMoviesRequest.class, Trendingmovies.TopMoviesRequest.Builder.class);
      }

      // Construct using Trendingmovies.TopMoviesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        count_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trendingmovies.internal_static_TopMoviesRequest_descriptor;
      }

      public Trendingmovies.TopMoviesRequest getDefaultInstanceForType() {
        return Trendingmovies.TopMoviesRequest.getDefaultInstance();
      }

      public Trendingmovies.TopMoviesRequest build() {
        Trendingmovies.TopMoviesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Trendingmovies.TopMoviesRequest buildPartial() {
        Trendingmovies.TopMoviesRequest result = new Trendingmovies.TopMoviesRequest(this);
        result.count_ = count_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Trendingmovies.TopMoviesRequest) {
          return mergeFrom((Trendingmovies.TopMoviesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Trendingmovies.TopMoviesRequest other) {
        if (other == Trendingmovies.TopMoviesRequest.getDefaultInstance()) return this;
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Trendingmovies.TopMoviesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Trendingmovies.TopMoviesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 1;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 1;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 1;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TopMoviesRequest)
    }

    // @@protoc_insertion_point(class_scope:TopMoviesRequest)
    private static final Trendingmovies.TopMoviesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Trendingmovies.TopMoviesRequest();
    }

    public static Trendingmovies.TopMoviesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopMoviesRequest>
        PARSER = new com.google.protobuf.AbstractParser<TopMoviesRequest>() {
      public TopMoviesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TopMoviesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopMoviesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopMoviesRequest> getParserForType() {
      return PARSER;
    }

    public Trendingmovies.TopMoviesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieRatingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MovieRating)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string movieId = 1;</code>
     */
    java.lang.String getMovieId();
    /**
     * <code>string movieId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMovieIdBytes();

    /**
     * <code>int32 rating = 2;</code>
     */
    int getRating();
  }
  /**
   * Protobuf type {@code MovieRating}
   */
  public  static final class MovieRating extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MovieRating)
      MovieRatingOrBuilder {
    // Use MovieRating.newBuilder() to construct.
    private MovieRating(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieRating() {
      movieId_ = "";
      rating_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieRating(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              movieId_ = s;
              break;
            }
            case 16: {

              rating_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trendingmovies.internal_static_MovieRating_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trendingmovies.internal_static_MovieRating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trendingmovies.MovieRating.class, Trendingmovies.MovieRating.Builder.class);
    }

    public static final int MOVIEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object movieId_;
    /**
     * <code>string movieId = 1;</code>
     */
    public java.lang.String getMovieId() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieId_ = s;
        return s;
      }
    }
    /**
     * <code>string movieId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMovieIdBytes() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATING_FIELD_NUMBER = 2;
    private int rating_;
    /**
     * <code>int32 rating = 2;</code>
     */
    public int getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMovieIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movieId_);
      }
      if (rating_ != 0) {
        output.writeInt32(2, rating_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMovieIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, movieId_);
      }
      if (rating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rating_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Trendingmovies.MovieRating)) {
        return super.equals(obj);
      }
      Trendingmovies.MovieRating other = (Trendingmovies.MovieRating) obj;

      boolean result = true;
      result = result && getMovieId()
          .equals(other.getMovieId());
      result = result && (getRating()
          == other.getRating());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieId().hashCode();
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRating();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Trendingmovies.MovieRating parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.MovieRating parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.MovieRating parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.MovieRating parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.MovieRating parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.MovieRating parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.MovieRating parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trendingmovies.MovieRating parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trendingmovies.MovieRating parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Trendingmovies.MovieRating parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trendingmovies.MovieRating parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trendingmovies.MovieRating parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Trendingmovies.MovieRating prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MovieRating}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MovieRating)
        Trendingmovies.MovieRatingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trendingmovies.internal_static_MovieRating_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trendingmovies.internal_static_MovieRating_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Trendingmovies.MovieRating.class, Trendingmovies.MovieRating.Builder.class);
      }

      // Construct using Trendingmovies.MovieRating.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        movieId_ = "";

        rating_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trendingmovies.internal_static_MovieRating_descriptor;
      }

      public Trendingmovies.MovieRating getDefaultInstanceForType() {
        return Trendingmovies.MovieRating.getDefaultInstance();
      }

      public Trendingmovies.MovieRating build() {
        Trendingmovies.MovieRating result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Trendingmovies.MovieRating buildPartial() {
        Trendingmovies.MovieRating result = new Trendingmovies.MovieRating(this);
        result.movieId_ = movieId_;
        result.rating_ = rating_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Trendingmovies.MovieRating) {
          return mergeFrom((Trendingmovies.MovieRating)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Trendingmovies.MovieRating other) {
        if (other == Trendingmovies.MovieRating.getDefaultInstance()) return this;
        if (!other.getMovieId().isEmpty()) {
          movieId_ = other.movieId_;
          onChanged();
        }
        if (other.getRating() != 0) {
          setRating(other.getRating());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Trendingmovies.MovieRating parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Trendingmovies.MovieRating) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object movieId_ = "";
      /**
       * <code>string movieId = 1;</code>
       */
      public java.lang.String getMovieId() {
        java.lang.Object ref = movieId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          movieId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMovieIdBytes() {
        java.lang.Object ref = movieId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          movieId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       */
      public Builder setMovieId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       */
      public Builder clearMovieId() {
        
        movieId_ = getDefaultInstance().getMovieId();
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       */
      public Builder setMovieIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        movieId_ = value;
        onChanged();
        return this;
      }

      private int rating_ ;
      /**
       * <code>int32 rating = 2;</code>
       */
      public int getRating() {
        return rating_;
      }
      /**
       * <code>int32 rating = 2;</code>
       */
      public Builder setRating(int value) {
        
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rating = 2;</code>
       */
      public Builder clearRating() {
        
        rating_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MovieRating)
    }

    // @@protoc_insertion_point(class_scope:MovieRating)
    private static final Trendingmovies.MovieRating DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Trendingmovies.MovieRating();
    }

    public static Trendingmovies.MovieRating getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieRating>
        PARSER = new com.google.protobuf.AbstractParser<MovieRating>() {
      public MovieRating parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieRating(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieRating> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieRating> getParserForType() {
      return PARSER;
    }

    public Trendingmovies.MovieRating getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TopMoviesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopMoviesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    java.util.List<Trendingmovies.MovieRating> 
        getRatingsList();
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    Trendingmovies.MovieRating getRatings(int index);
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    int getRatingsCount();
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    java.util.List<? extends Trendingmovies.MovieRatingOrBuilder> 
        getRatingsOrBuilderList();
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    Trendingmovies.MovieRatingOrBuilder getRatingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TopMoviesResponse}
   */
  public  static final class TopMoviesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopMoviesResponse)
      TopMoviesResponseOrBuilder {
    // Use TopMoviesResponse.newBuilder() to construct.
    private TopMoviesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopMoviesResponse() {
      ratings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TopMoviesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ratings_ = new java.util.ArrayList<Trendingmovies.MovieRating>();
                mutable_bitField0_ |= 0x00000001;
              }
              ratings_.add(
                  input.readMessage(Trendingmovies.MovieRating.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ratings_ = java.util.Collections.unmodifiableList(ratings_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trendingmovies.internal_static_TopMoviesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trendingmovies.internal_static_TopMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trendingmovies.TopMoviesResponse.class, Trendingmovies.TopMoviesResponse.Builder.class);
    }

    public static final int RATINGS_FIELD_NUMBER = 1;
    private java.util.List<Trendingmovies.MovieRating> ratings_;
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    public java.util.List<Trendingmovies.MovieRating> getRatingsList() {
      return ratings_;
    }
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    public java.util.List<? extends Trendingmovies.MovieRatingOrBuilder> 
        getRatingsOrBuilderList() {
      return ratings_;
    }
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    public int getRatingsCount() {
      return ratings_.size();
    }
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    public Trendingmovies.MovieRating getRatings(int index) {
      return ratings_.get(index);
    }
    /**
     * <code>repeated .MovieRating ratings = 1;</code>
     */
    public Trendingmovies.MovieRatingOrBuilder getRatingsOrBuilder(
        int index) {
      return ratings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ratings_.size(); i++) {
        output.writeMessage(1, ratings_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ratings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ratings_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Trendingmovies.TopMoviesResponse)) {
        return super.equals(obj);
      }
      Trendingmovies.TopMoviesResponse other = (Trendingmovies.TopMoviesResponse) obj;

      boolean result = true;
      result = result && getRatingsList()
          .equals(other.getRatingsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRatingsCount() > 0) {
        hash = (37 * hash) + RATINGS_FIELD_NUMBER;
        hash = (53 * hash) + getRatingsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Trendingmovies.TopMoviesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Trendingmovies.TopMoviesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trendingmovies.TopMoviesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Trendingmovies.TopMoviesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopMoviesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopMoviesResponse)
        Trendingmovies.TopMoviesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trendingmovies.internal_static_TopMoviesResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trendingmovies.internal_static_TopMoviesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Trendingmovies.TopMoviesResponse.class, Trendingmovies.TopMoviesResponse.Builder.class);
      }

      // Construct using Trendingmovies.TopMoviesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRatingsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (ratingsBuilder_ == null) {
          ratings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ratingsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trendingmovies.internal_static_TopMoviesResponse_descriptor;
      }

      public Trendingmovies.TopMoviesResponse getDefaultInstanceForType() {
        return Trendingmovies.TopMoviesResponse.getDefaultInstance();
      }

      public Trendingmovies.TopMoviesResponse build() {
        Trendingmovies.TopMoviesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Trendingmovies.TopMoviesResponse buildPartial() {
        Trendingmovies.TopMoviesResponse result = new Trendingmovies.TopMoviesResponse(this);
        int from_bitField0_ = bitField0_;
        if (ratingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            ratings_ = java.util.Collections.unmodifiableList(ratings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ratings_ = ratings_;
        } else {
          result.ratings_ = ratingsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Trendingmovies.TopMoviesResponse) {
          return mergeFrom((Trendingmovies.TopMoviesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Trendingmovies.TopMoviesResponse other) {
        if (other == Trendingmovies.TopMoviesResponse.getDefaultInstance()) return this;
        if (ratingsBuilder_ == null) {
          if (!other.ratings_.isEmpty()) {
            if (ratings_.isEmpty()) {
              ratings_ = other.ratings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRatingsIsMutable();
              ratings_.addAll(other.ratings_);
            }
            onChanged();
          }
        } else {
          if (!other.ratings_.isEmpty()) {
            if (ratingsBuilder_.isEmpty()) {
              ratingsBuilder_.dispose();
              ratingsBuilder_ = null;
              ratings_ = other.ratings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ratingsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRatingsFieldBuilder() : null;
            } else {
              ratingsBuilder_.addAllMessages(other.ratings_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Trendingmovies.TopMoviesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Trendingmovies.TopMoviesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Trendingmovies.MovieRating> ratings_ =
        java.util.Collections.emptyList();
      private void ensureRatingsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ratings_ = new java.util.ArrayList<Trendingmovies.MovieRating>(ratings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Trendingmovies.MovieRating, Trendingmovies.MovieRating.Builder, Trendingmovies.MovieRatingOrBuilder> ratingsBuilder_;

      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public java.util.List<Trendingmovies.MovieRating> getRatingsList() {
        if (ratingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ratings_);
        } else {
          return ratingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public int getRatingsCount() {
        if (ratingsBuilder_ == null) {
          return ratings_.size();
        } else {
          return ratingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Trendingmovies.MovieRating getRatings(int index) {
        if (ratingsBuilder_ == null) {
          return ratings_.get(index);
        } else {
          return ratingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder setRatings(
          int index, Trendingmovies.MovieRating value) {
        if (ratingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatingsIsMutable();
          ratings_.set(index, value);
          onChanged();
        } else {
          ratingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder setRatings(
          int index, Trendingmovies.MovieRating.Builder builderForValue) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.set(index, builderForValue.build());
          onChanged();
        } else {
          ratingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder addRatings(Trendingmovies.MovieRating value) {
        if (ratingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatingsIsMutable();
          ratings_.add(value);
          onChanged();
        } else {
          ratingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder addRatings(
          int index, Trendingmovies.MovieRating value) {
        if (ratingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatingsIsMutable();
          ratings_.add(index, value);
          onChanged();
        } else {
          ratingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder addRatings(
          Trendingmovies.MovieRating.Builder builderForValue) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.add(builderForValue.build());
          onChanged();
        } else {
          ratingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder addRatings(
          int index, Trendingmovies.MovieRating.Builder builderForValue) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.add(index, builderForValue.build());
          onChanged();
        } else {
          ratingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder addAllRatings(
          java.lang.Iterable<? extends Trendingmovies.MovieRating> values) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ratings_);
          onChanged();
        } else {
          ratingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder clearRatings() {
        if (ratingsBuilder_ == null) {
          ratings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ratingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Builder removeRatings(int index) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.remove(index);
          onChanged();
        } else {
          ratingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Trendingmovies.MovieRating.Builder getRatingsBuilder(
          int index) {
        return getRatingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Trendingmovies.MovieRatingOrBuilder getRatingsOrBuilder(
          int index) {
        if (ratingsBuilder_ == null) {
          return ratings_.get(index);  } else {
          return ratingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public java.util.List<? extends Trendingmovies.MovieRatingOrBuilder> 
           getRatingsOrBuilderList() {
        if (ratingsBuilder_ != null) {
          return ratingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ratings_);
        }
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Trendingmovies.MovieRating.Builder addRatingsBuilder() {
        return getRatingsFieldBuilder().addBuilder(
            Trendingmovies.MovieRating.getDefaultInstance());
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public Trendingmovies.MovieRating.Builder addRatingsBuilder(
          int index) {
        return getRatingsFieldBuilder().addBuilder(
            index, Trendingmovies.MovieRating.getDefaultInstance());
      }
      /**
       * <code>repeated .MovieRating ratings = 1;</code>
       */
      public java.util.List<Trendingmovies.MovieRating.Builder> 
           getRatingsBuilderList() {
        return getRatingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Trendingmovies.MovieRating, Trendingmovies.MovieRating.Builder, Trendingmovies.MovieRatingOrBuilder> 
          getRatingsFieldBuilder() {
        if (ratingsBuilder_ == null) {
          ratingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Trendingmovies.MovieRating, Trendingmovies.MovieRating.Builder, Trendingmovies.MovieRatingOrBuilder>(
                  ratings_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          ratings_ = null;
        }
        return ratingsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TopMoviesResponse)
    }

    // @@protoc_insertion_point(class_scope:TopMoviesResponse)
    private static final Trendingmovies.TopMoviesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Trendingmovies.TopMoviesResponse();
    }

    public static Trendingmovies.TopMoviesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopMoviesResponse>
        PARSER = new com.google.protobuf.AbstractParser<TopMoviesResponse>() {
      public TopMoviesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TopMoviesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopMoviesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopMoviesResponse> getParserForType() {
      return PARSER;
    }

    public Trendingmovies.TopMoviesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopMoviesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopMoviesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieRating_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieRating_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopMoviesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopMoviesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024trendingmovies.proto\"!\n\020TopMoviesReque" +
      "st\022\r\n\005count\030\001 \001(\005\".\n\013MovieRating\022\017\n\007movi" +
      "eId\030\001 \001(\t\022\016\n\006rating\030\002 \001(\005\"2\n\021TopMoviesRe" +
      "sponse\022\035\n\007ratings\030\001 \003(\0132\014.MovieRating2N\n" +
      "\025TrendingMoviesService\0225\n\014GetTopMovies\022\021" +
      ".TopMoviesRequest\032\022.TopMoviesResponseb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TopMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopMoviesRequest_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_MovieRating_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MovieRating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieRating_descriptor,
        new java.lang.String[] { "MovieId", "Rating", });
    internal_static_TopMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TopMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopMoviesResponse_descriptor,
        new java.lang.String[] { "Ratings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
